import type { DisplayPads } from "../font-metrics.js";
import type { ColorRoleName, FontRole, Preset } from "../roles.js";
import { buildTokens } from "../tokens.js";
import type { Token } from "../tokens.js";

/**
 * The stylesheet: primitives, then roles on `:root`, then the Tailwind mapping.
 *
 * Why three mapping blocks and not one:
 *   - `@theme inline` for colours, so `bg-surface` compiles to `var(--surface)` and
 *     `:root` stays the single definition;
 *   - a bare `@theme` for the names that are NOT also `:root` tokens (the type
 *     scale, radii, font stacks), emitted once by Tailwind;
 *   - `@theme inline reference` for the names that ARE both, `--shadow-*` and
 *     `--ease-*`: a plain inline entry would re-emit `--shadow-lift:
 *     var(--shadow-lift)` into the theme layer, a self-reference. `reference`
 *     compiles the utility and emits no variable.
 * That split was measured upstream (2026-09-14) by compiling both
 * forms and diffing the emitted rules; it is not a guess.
 */

const declaration = (token: Token) => `  ${token.cssVar}: ${token.value};`;

function fontFace(face: FontRole, urlBase: string): string {
  return [
    "@font-face {",
    `  font-family: "${face.family}";`,
    `  font-style: ${face.style};`,
    `  font-weight: ${face.weight};`,
    "  font-display: swap;",
    `  src: url("${urlBase}${face.file}") format("woff2");`,
    "}",
  ].join("\n");
}

export interface CssEmitOptions {
  /** Prefix for the `@font-face` src URLs. Relative to the stylesheet by default. */
  fontUrlBase?: string;
}

export function emitCss(preset: Preset, pads: DisplayPads, options: CssEmitOptions = {}): string {
  const urlBase = options.fontUrlBase ?? "./fonts/";
  const tokens = buildTokens(preset, pads);
  const tier = (name: Token["tier"]) => tokens.filter((t) => t.tier === name);
  const roleNames = Object.keys(preset.color) as ColorRoleName[];

  const out: string[] = [];
  out.push(
    "/* @marquee-ui/tokens - preset: " +
      preset.name +
      "\n   GENERATED by `pnpm build`; edit the preset, never this file.\n" +
      "   Pads are measured from the display woff2, not typed. */",
    "",
    // The faces ship WITH the preset (D8): a preset that names a family it does not
    // load is a preset that renders as a fallback.
    [preset.fonts.display, preset.fonts.body, preset.fonts.mono]
      .map((face) => fontFace(face, urlBase))
      .join("\n"),
    "",
    "/* Tier 1: primitives. The only colour literals in the package. */",
    ":root {",
    ...tier("primitive").map(declaration),
    "}",
    "",
    "/* Tier 2: roles. What the system talks in; every colour is a primitive. */",
    ":root {",
    `  color-scheme: ${preset.colorScheme};`,
    "",
    ...tier("role").map(declaration),
    "}",
    "",
    "/* Reduced motion: every transition and the ticker stop. */",
    "@media (prefers-reduced-motion: reduce) {",
    "  :root {",
    "    --dur-fast: 0ms;",
    "    --dur-base: 0ms;",
    "  }",
    "}",
    "",
    "/* Tier 3: the Tailwind mapping. */",
    "@theme {",
    ...tier("theme").map(declaration),
    "}",
    "",
    "@theme inline {",
    ...roleNames.map((role) => `  --color-${role}: var(--${role});`),
    "",
    "  --spacing-hit: var(--hit-min);",
    "  --container-content: var(--content-max);",
    "  --container-page: var(--page-max);",
    "}",
    "",
    "@theme inline reference {",
    "  --shadow-sm: var(--shadow-sm);",
    "  --shadow-md: var(--shadow-md);",
    "  --shadow-lg: var(--shadow-lg);",
    "  --shadow-lift: var(--shadow-lift);",
    "  --shadow-focus-ring: var(--shadow-focus-ring);",
    "  --ease-standard: var(--ease-standard);",
    "  --ease-emphasis: var(--ease-emphasis);",
    "}",
    "",
  );
  return out.join("\n");
}

/**
 * The custom properties a stylesheet DECLARES, which is not the same as the ones it
 * mentions: `@theme inline` blocks are the Tailwind mapping, so their entries are
 * aliases of tokens declared elsewhere and are skipped. Comments are stripped first,
 * so a token named in prose is not mistaken for one that exists.
 */
export function declaredCssVars(css: string): string[] {
  const stripped = css.replace(/\/\*[\s\S]*?\*\//g, "");
  const names = new Set<string>();
  let depth = 0;
  let skipUntilDepth: number | null = null;

  for (const line of stripped.split("\n")) {
    const opens = (line.match(/\{/g) ?? []).length;
    const closes = (line.match(/\}/g) ?? []).length;
    const isInlineTheme = /@theme\s+inline\b/.test(line);

    if (skipUntilDepth === null && isInlineTheme) skipUntilDepth = depth;

    if (skipUntilDepth === null) {
      const match = /^\s*(--[A-Za-z0-9_-]+)\s*:/.exec(line);
      if (match?.[1]) names.add(match[1]);
    }

    depth += opens - closes;
    if (skipUntilDepth !== null && depth <= skipUntilDepth) skipUntilDepth = null;
  }
  return [...names].sort();
}
